### PR TITLE
 1st commit

### PR DESCRIPTION
**Pull request by suryasuresh06**
Surya Suresh

### CODE REVIEW

**Comment by iev6** [comment]
Hi, good job! I see some empty lines, did you have trouble with anything?

**Comment by iev6** [comment]
you can write back to me on my email. we will add you to IITMCVG organization.

**Comment by suryasuresh06** [comment]
I found linear algebra hard. couldnt understand the decompositions. thats why i left it empty.
ThanksSurya


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Giridhur S <notifications@github.com> Date: 13/12/2016  14:49  (GMT+05:30) To: iitmcvg/numpy_exercises <numpy_exercises@noreply.github.com> Cc: suryasuresh06 <suryaallstars06@gmail.com>, Author <author@noreply.github.com> Subject: Re: [iitmcvg/numpy_exercises] 1st commit (#1) 
Hi, good job! I see some empty lines, did you have trouble with anything?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iitmcvg/numpy_exercises","title":"iitmcvg/numpy_exercises","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iitmcvg/numpy_exercises"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iev6 in #1: Hi, good job! I see some empty lines, did you have trouble with anything?"}],"action":{"name":"View Pull Request","url":"https://github.com/iitmcvg/numpy_exercises/pull/1#issuecomment-266686920"}}}

**Comment by iev6** [comment]
Ah it's alright. I assume you didnt get Cholesky Decomposition ,
EigenValue,EigenVector etc?



ᐧ

*Giridhur S *
Undergraduate Senior
Electrical Engineering
Indian Institute of Technology,Madras

**Comment by suryasuresh06** [comment]
Yes. i tried checking it online but i still couldnt understand it well
enough

Surya

**Comment by iev6** [comment]
We will organise a session on them next semester. You can see this page :
http://people.revoledu.com/kardi/tutorial/LinearAlgebra/
or this page https://www.khanacademy.org/math/linear-algebra , if you want
to get a head start.

If you get stuck in between somewhere, dont be shy, ping me directly @
giridhursriram@gmail.com or any of the other club heads members.

Cheers,
Giridhur S.


ᐧ

*Giridhur S *
Undergraduate Senior
Electrical Engineering
Indian Institute of Technology,Madras

**Comment by iev6** [comment]
This is also pretty good : https://www.math.ucdavis.edu/~linear/linear.pdf
ᐧ

*Giridhur S *
Undergraduate Senior
Electrical Engineering
Indian Institute of Technology,Madras

**Comment by suryasuresh06** [comment]
Ok thanks a lot for all the help. will definitely ping u in case of any doubts.
Surya


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Giridhur S <notifications@github.com> Date: 13/12/2016  15:40  (GMT+05:30) To: iitmcvg/numpy_exercises <numpy_exercises@noreply.github.com> Cc: suryasuresh06 <suryaallstars06@gmail.com>, Author <author@noreply.github.com> Subject: Re: [iitmcvg/numpy_exercises] 1st commit (#1) 
We will organise a session on them next semester. You can see this page :

http://people.revoledu.com/kardi/tutorial/LinearAlgebra/

or this page https://www.khanacademy.org/math/linear-algebra , if you want

to get a head start.



If you get stuck in between somewhere, dont be shy, ping me directly @

giridhursriram@gmail.com or any of the other club heads members.



Cheers,

Giridhur S.





ᐧ



*Giridhur S *

Undergraduate Senior

Electrical Engineering

Indian Institute of Technology,Madras





On Tue, Dec 13, 2016 at 3:33 PM, suryasuresh06 <notifications@github.com>

wrote:



> Yes. i tried checking it online but i still couldnt understand it well

> enough

>

> Surya

>

**Pull request closed without merging**
