### PR TITLE
Ananthu545 patch 1

### PR DESCRIPTION
**Pull request by ananthu545**

### CODE REVIEW

**Comment by rsnk96** [comment]
Hey Ananth

Nice work. Did you face difficulties anywhere?

**Comment by rsnk96** [comment]
Also, fill in your details here

https://docs.google.com/forms/d/e/1FAIpQLScVmctoC-LfU7qDop3diGj9FnzqTFGRYUAHA5JNl0fyUWQQaA/viewform#responses

**Comment by ananthu545** [comment]
I couldn't understand Eigen vector , eigen values and some other stuff in linalg

**Comment by rsnk96** [comment]
We'll hold a Lin Al basics sessions next sem. You should get them cleared then.

**Pull request closed without merging**
